In [1]:
import numpy as np

In [3]:
M = np.array([[1,-1],[6,4]])
M

array([[ 1, -1],
       [ 6,  4]])

In [13]:
eigval, eigvec = np.linalg.eig(M)

In [14]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [15]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

vector [1,3] bukan eigenvector dari matrix [[1,-1],[6,4]]