In [2]:
import numpy as np

In [7]:
def f(x,y):
    return 3 * x + 4 * y -5

f1 = 3 * x + 4 * y -5

In [10]:
x = np.linspace(0,20)
y = np.linspace(0,20)

z = np.array([[f(i,j) for i in x] for j in y])

dx,dy=np.gradient(z)

In [11]:
dx1 = np.gradient(f1,x)
dy1 = np.gradient(f1,y)

In [14]:
dx

array([[1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       ...,
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306]])

In [12]:
dx1

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [24]:
dy

array([[0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       ...,
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041]])

In [13]:
dy1

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])